// This file is @generated by prost-build.
/// 插件信息 / Plugin Information
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PluginInfo {
    /// 插件唯一编号 / Plugin unique number
    #[prost(string, tag = "1")]
    pub no: ::prost::alloc::string::String,
    /// 插件名称 / Plugin name
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// 插件拥有的方法 / Methods owned by plugin
    #[prost(string, repeated, tag = "3")]
    pub methods: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 插件版本 / Plugin version
    #[prost(string, tag = "4")]
    pub version: ::prost::alloc::string::String,
    /// 插件优先级, 数字越大优先级越高 / Plugin priority, higher number means
    /// higher priority
    #[prost(int32, tag = "5")]
    pub priority: i32,
    /// PersistAfter方法是否同步调用 / Whether PersistAfter method is called
    /// synchronously
    #[prost(bool, tag = "6")]
    pub persist_after_sync: bool,
    /// Reply方法是否同步调用 / Whether Reply method is called synchronously
    #[prost(bool, tag = "7")]
    pub reply_sync: bool,
    /// 插件配置模版 / Plugin configuration template
    #[prost(message, optional, tag = "8")]
    pub config_template: ::core::option::Option<ConfigTemplate>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Field {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub label: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConfigTemplate {
    #[prost(message, repeated, tag = "1")]
    pub fields: ::prost::alloc::vec::Vec<Field>,
}
/// 插件启动返回 / Plugin startup response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartupResp {
    /// 节点id / Node id
    #[prost(uint64, tag = "1")]
    pub node_id: u64,
    /// 是否成功 / Whether successful
    #[prost(bool, tag = "2")]
    pub success: bool,
    /// 错误信息 / Error message
    #[prost(string, tag = "3")]
    pub err_msg: ::prost::alloc::string::String,
    /// 沙盒路径 / Sandbox directory
    #[prost(string, tag = "4")]
    pub sandbox_dir: ::prost::alloc::string::String,
    /// 配置 / Configuration
    #[prost(bytes = "vec", tag = "5")]
    pub config: ::prost::alloc::vec::Vec<u8>,
}
/// 连接信息 / Connection information
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Conn {
    /// 用户uid / User uid
    #[prost(string, tag = "1")]
    pub uid: ::prost::alloc::string::String,
    /// 连接id / Connection id
    #[prost(int64, tag = "2")]
    pub conn_id: i64,
    /// 设备id / Device id
    #[prost(string, tag = "3")]
    pub device_id: ::prost::alloc::string::String,
    /// 设备标志 / Device flag
    #[prost(uint32, tag = "4")]
    pub device_flag: u32,
    /// 设备等级 / Device level
    #[prost(uint32, tag = "5")]
    pub device_level: u32,
}
/// 发送包 / Send packet
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendPacket {
    /// 发送者 / Sender
    #[prost(string, tag = "1")]
    pub from_uid: ::prost::alloc::string::String,
    /// 接收频道 / Receive channel
    #[prost(string, tag = "2")]
    pub channel_id: ::prost::alloc::string::String,
    /// 频道类型 / Channel type
    #[prost(uint32, tag = "3")]
    pub channel_type: u32,
    /// 消息内容 / Message content
    #[prost(bytes = "vec", tag = "4")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    /// 错误原因（默认为成功）/ Error reason (default is success)
    #[prost(uint32, tag = "5")]
    pub reason: u32,
    /// 发送者的连接 / Sender's connection
    #[prost(message, optional, tag = "6")]
    pub conn: ::core::option::Option<Conn>,
}
/// 接收包 / Receive packet
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecvPacket {
    /// 发送者 / Sender
    #[prost(string, tag = "1")]
    pub from_uid: ::prost::alloc::string::String,
    /// 接受者 / Receiver
    #[prost(string, tag = "2")]
    pub to_uid: ::prost::alloc::string::String,
    /// 接收频道 / Receive channel
    #[prost(string, tag = "3")]
    pub channel_id: ::prost::alloc::string::String,
    /// 频道类型 / Channel type
    #[prost(uint32, tag = "4")]
    pub channel_type: u32,
    /// 消息内容 / Message content
    #[prost(bytes = "vec", tag = "5")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
/// 消息 / Message
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
    /// 消息唯一id（全局唯一）/ Message unique id (globally unique)
    #[prost(int64, tag = "1")]
    pub message_id: i64,
    /// 消息序号（频道内严格递增）/ Message sequence number (strictly increasing
    /// within channel)
    #[prost(uint64, tag = "2")]
    pub message_seq: u64,
    /// 客户端消息编号 / Client message number
    #[prost(string, tag = "3")]
    pub client_msg_no: ::prost::alloc::string::String,
    /// 流编号 / Stream number
    #[prost(string, tag = "4")]
    pub stream_no: ::prost::alloc::string::String,
    /// 流序号 / Stream sequence
    #[prost(uint64, tag = "5")]
    pub stream_id: u64,
    /// 消息时间戳 / Message timestamp
    #[prost(uint32, tag = "6")]
    pub timestamp: u32,
    /// 发送者 / Sender
    #[prost(string, tag = "7")]
    pub from: ::prost::alloc::string::String,
    /// 接收频道 / Receive channel
    #[prost(string, tag = "8")]
    pub channel_id: ::prost::alloc::string::String,
    /// 频道类型 / Channel type
    #[prost(uint32, tag = "9")]
    pub channel_type: u32,
    /// topic
    #[prost(string, tag = "10")]
    pub topic: ::prost::alloc::string::String,
    /// 消息内容 / Message content
    #[prost(bytes = "vec", tag = "11")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageBatch {
    #[prost(message, repeated, tag = "1")]
    pub messages: ::prost::alloc::vec::Vec<Message>,
}
/// http请求 / HTTP request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HttpRequest {
    /// 请求方法 / Request method
    #[prost(string, tag = "1")]
    pub method: ::prost::alloc::string::String,
    /// 请求路径 / Request path
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    /// 请求头 / Request headers
    #[prost(map = "string, string", tag = "3")]
    pub headers: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// 查询参数 / Query parameters
    #[prost(map = "string, string", tag = "4")]
    pub query: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// 请求体 / Request body
    #[prost(bytes = "vec", tag = "5")]
    pub body: ::prost::alloc::vec::Vec<u8>,
}
/// http响应 / HTTP response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HttpResponse {
    /// 状态码 / Status code
    #[prost(int32, tag = "1")]
    pub status: i32,
    /// 响应头 / Response headers
    #[prost(map = "string, string", tag = "2")]
    pub headers: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// 响应体 / Response body
    #[prost(bytes = "vec", tag = "3")]
    pub body: ::prost::alloc::vec::Vec<u8>,
}
/// 频道消息请求 / Channel message request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChannelMessageReq {
    /// 频道id / Channel id
    #[prost(string, tag = "1")]
    pub channel_id: ::prost::alloc::string::String,
    /// 频道类型 / Channel type
    #[prost(uint32, tag = "2")]
    pub channel_type: u32,
    /// 消息开始序号 / Start message sequence
    #[prost(uint64, tag = "3")]
    pub start_message_seq: u64,
    /// 查询数量，默认100 / Query limit, default 100
    #[prost(uint32, tag = "4")]
    pub limit: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChannelMessageBatchReq {
    #[prost(message, repeated, tag = "1")]
    pub channel_message_reqs: ::prost::alloc::vec::Vec<ChannelMessageReq>,
}
/// 频道消息响应 / Channel message response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChannelMessageResp {
    /// 频道id / Channel id
    #[prost(string, tag = "1")]
    pub channel_id: ::prost::alloc::string::String,
    /// 频道类型 / Channel type
    #[prost(uint32, tag = "2")]
    pub channel_type: u32,
    /// 消息开始序号 / Start message sequence
    #[prost(uint64, tag = "3")]
    pub start_message_seq: u64,
    /// 查询数量，默认100 / Query limit, default 100
    #[prost(uint32, tag = "4")]
    pub limit: u32,
    /// 消息列表 / Message list
    #[prost(message, repeated, tag = "5")]
    pub messages: ::prost::alloc::vec::Vec<Message>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChannelMessageBatchResp {
    #[prost(message, repeated, tag = "1")]
    pub channel_message_resps: ::prost::alloc::vec::Vec<ChannelMessageResp>,
}
/// wukongim的分布式配置 / WuKongIM distributed configuration
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClusterConfig {
    /// 分布式中的节点 / Nodes in distributed system
    #[prost(message, repeated, tag = "1")]
    pub nodes: ::prost::alloc::vec::Vec<Node>,
    /// 分布式中的槽位 / Slots in distributed system
    #[prost(message, repeated, tag = "2")]
    pub slots: ::prost::alloc::vec::Vec<Slot>,
}
/// wk节点 / WK node
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Node {
    /// 节点id / Node id
    #[prost(uint64, tag = "1")]
    pub id: u64,
    /// 节点分布式通讯地址 / Node distributed communication address
    #[prost(string, tag = "2")]
    pub cluster_addr: ::prost::alloc::string::String,
    /// 节点api服务地址 / Node API service address
    #[prost(string, tag = "3")]
    pub api_server_addr: ::prost::alloc::string::String,
    /// 是否在线 / Whether online
    #[prost(bool, tag = "4")]
    pub online: bool,
}
/// wk的slot / WK slot
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Slot {
    /// 槽位id / Slot id
    #[prost(uint32, tag = "1")]
    pub id: u32,
    /// 槽位的领导节点 / Slot leader node
    #[prost(uint64, tag = "2")]
    pub leader: u64,
    /// 槽位的领导任期 / Slot leader term
    #[prost(uint32, tag = "3")]
    pub term: u32,
    /// 副本节点(包含领导节点) / Replica nodes (including leader)
    #[prost(uint64, repeated, tag = "4")]
    pub replicas: ::prost::alloc::vec::Vec<u64>,
}
/// 频道对象 / Channel object
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Channel {
    /// 频道id / Channel id
    #[prost(string, tag = "1")]
    pub channel_id: ::prost::alloc::string::String,
    /// 频道类型 / Channel type
    #[prost(uint32, tag = "2")]
    pub channel_type: u32,
}
/// 频道节点请求 / Channel node request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClusterChannelBelongNodeReq {
    /// 频道列表 / Channel list
    #[prost(message, repeated, tag = "1")]
    pub channels: ::prost::alloc::vec::Vec<Channel>,
}
/// 频道节点响应 / Channel node response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClusterChannelBelongNodeResp {
    /// 频道节点Id / Channel node Id
    #[prost(uint64, tag = "1")]
    pub node_id: u64,
    /// 频道列表 / Channel list
    #[prost(message, repeated, tag = "2")]
    pub channels: ::prost::alloc::vec::Vec<Channel>,
}
/// 频道节点批量响应 / Channel node batch response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClusterChannelBelongNodeBatchResp {
    #[prost(message, repeated, tag = "1")]
    pub cluster_channel_belong_node_resps: ::prost::alloc::vec::Vec<
        ClusterChannelBelongNodeResp,
    >,
}
/// http请求转发 / HTTP request forwarding
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ForwardHttpReq {
    /// 插件编号 / Plugin number
    #[prost(string, tag = "1")]
    pub plugin_no: ::prost::alloc::string::String,
    /// 目标节点id,如果为0则表示本节点,-1为所有节点 / Target node id, 0 means this
    /// node, -1 means all nodes
    #[prost(int64, tag = "2")]
    pub to_node_id: i64,
    /// 请求 / Request
    #[prost(message, optional, tag = "3")]
    pub request: ::core::option::Option<HttpRequest>,
}
/// 最近会话频道请求 / Recent conversation channel request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConversationChannelReq {
    /// 用户uid / User uid
    #[prost(string, tag = "1")]
    pub uid: ::prost::alloc::string::String,
}
/// 最近会话频道响应 / Recent conversation channel response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConversationChannelResp {
    /// 频道列表 / Channel list
    #[prost(message, repeated, tag = "1")]
    pub channels: ::prost::alloc::vec::Vec<Channel>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Header {
    /// 是否持久化 / Whether to persist
    #[prost(bool, tag = "1")]
    pub no_persist: bool,
    /// 是否红点 / Whether red dot
    #[prost(bool, tag = "2")]
    pub red_dot: bool,
    /// 是否同步一次 / Whether sync once
    #[prost(bool, tag = "3")]
    pub sync_once: bool,
}
/// 流基本信息 / Stream basic information
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Stream {
    /// 头部 / Header
    #[prost(message, optional, tag = "1")]
    pub header: ::core::option::Option<Header>,
    /// 客户端消息编号（相同编号，客户端只会显示一条，可以为空）/ Client message
    /// number (same number, client will only show one, can be empty)
    #[prost(string, tag = "2")]
    pub client_msg_no: ::prost::alloc::string::String,
    /// 发送者uid / Sender uid
    #[prost(string, tag = "3")]
    pub from_uid: ::prost::alloc::string::String,
    /// 频道id / Channel id
    #[prost(string, tag = "4")]
    pub channel_id: ::prost::alloc::string::String,
    /// 频道类型 / Channel type
    #[prost(uint32, tag = "5")]
    pub channel_type: u32,
    /// 消息内容 / Message content
    #[prost(bytes = "vec", tag = "6")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
/// 流开启结果 / Stream open response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamOpenResp {
    /// 流编号 / Stream number
    #[prost(string, tag = "1")]
    pub stream_no: ::prost::alloc::string::String,
}
/// 流关闭请求 / Stream close request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamCloseReq {
    /// 流编号 / Stream number
    #[prost(string, tag = "1")]
    pub stream_no: ::prost::alloc::string::String,
    /// 频道id / Channel id
    #[prost(string, tag = "2")]
    pub channel_id: ::prost::alloc::string::String,
    /// 频道类型 / Channel type
    #[prost(uint32, tag = "3")]
    pub channel_type: u32,
}
/// 流写入请求 / Stream write request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamWriteReq {
    /// 头部 / Header
    #[prost(message, optional, tag = "1")]
    pub header: ::core::option::Option<Header>,
    /// 流编号 / Stream number
    #[prost(string, tag = "2")]
    pub stream_no: ::prost::alloc::string::String,
    /// 客户端消息编号（相同编号，客户端只会显示一条，可以为空）/ Client message
    /// number (same number, client will only show one, can be empty)
    #[prost(string, tag = "3")]
    pub client_msg_no: ::prost::alloc::string::String,
    /// 发送者uid / Sender uid
    #[prost(string, tag = "4")]
    pub from_uid: ::prost::alloc::string::String,
    /// 频道id / Channel id
    #[prost(string, tag = "5")]
    pub channel_id: ::prost::alloc::string::String,
    /// 频道类型 / Channel type
    #[prost(uint32, tag = "6")]
    pub channel_type: u32,
    /// 消息内容 / Message content
    #[prost(bytes = "vec", tag = "7")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
/// 流写入结果 / Stream write response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamWriteResp {
    /// 消息唯一id（全局唯一）/ Message unique id (globally unique)
    #[prost(int64, tag = "1")]
    pub message_id: i64,
    /// 客户端消息编号 / Client message number
    #[prost(string, tag = "2")]
    pub client_msg_no: ::prost::alloc::string::String,
}
/// 发送消息请求 / Send message request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendReq {
    /// 头部 / Header
    #[prost(message, optional, tag = "1")]
    pub header: ::core::option::Option<Header>,
    /// 客户端消息编号（相同编号，客户端只会显示一条，可以为空）/ Client message
    /// number (same number, client will only show one, can be empty)
    #[prost(string, tag = "2")]
    pub client_msg_no: ::prost::alloc::string::String,
    /// 发送者 / Sender
    #[prost(string, tag = "3")]
    pub from_uid: ::prost::alloc::string::String,
    /// 频道id / Channel id
    #[prost(string, tag = "4")]
    pub channel_id: ::prost::alloc::string::String,
    /// 频道类型 / Channel type
    #[prost(uint32, tag = "5")]
    pub channel_type: u32,
    /// 消息内容 / Message content
    #[prost(bytes = "vec", tag = "6")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
/// 发送消息响应 / Send message response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendResp {
    /// 消息唯一id（全局唯一）/ Message unique id (globally unique)
    #[prost(int64, tag = "1")]
    pub message_id: i64,
}
/// 空响应 / Empty response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Empty {}
/// Generated client implementations.
pub mod plugin_service_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// 插件服务 / Plugin Service
    /// 注意：WuKongIM 的插件服务通常由插件实现，服务器调用插件的方法
    /// Note: WuKongIM's plugin service is usually implemented by plugins, and the
    /// server calls plugin methods
    #[derive(Debug, Clone)]
    pub struct PluginServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl PluginServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> PluginServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> PluginServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            PluginServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// 插件启动 / Plugin startup
        pub async fn startup(
            &mut self,
            request: impl tonic::IntoRequest<super::PluginInfo>,
        ) -> std::result::Result<tonic::Response<super::StartupResp>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pluginproto.PluginService/Startup",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pluginproto.PluginService", "Startup"));
            self.inner.unary(req, path, codec).await
        }
        /// 处理发送包（消息发送前）/ Handle send packet (before message sent)
        pub async fn on_send_packet(
            &mut self,
            request: impl tonic::IntoRequest<super::SendPacket>,
        ) -> std::result::Result<tonic::Response<super::SendPacket>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pluginproto.PluginService/OnSendPacket",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pluginproto.PluginService", "OnSendPacket"));
            self.inner.unary(req, path, codec).await
        }
        /// 处理接收包（消息接收后）/ Handle receive packet (after message received)
        pub async fn on_recv_packet(
            &mut self,
            request: impl tonic::IntoRequest<super::RecvPacket>,
        ) -> std::result::Result<tonic::Response<super::RecvPacket>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pluginproto.PluginService/OnRecvPacket",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pluginproto.PluginService", "OnRecvPacket"));
            self.inner.unary(req, path, codec).await
        }
        /// 处理消息持久化后 / Handle after message persisted
        pub async fn on_persist_after(
            &mut self,
            request: impl tonic::IntoRequest<super::Message>,
        ) -> std::result::Result<tonic::Response<super::Message>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pluginproto.PluginService/OnPersistAfter",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pluginproto.PluginService", "OnPersistAfter"));
            self.inner.unary(req, path, codec).await
        }
        /// 处理回复消息 / Handle reply message
        pub async fn on_reply(
            &mut self,
            request: impl tonic::IntoRequest<super::Message>,
        ) -> std::result::Result<tonic::Response<super::Message>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pluginproto.PluginService/OnReply",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pluginproto.PluginService", "OnReply"));
            self.inner.unary(req, path, codec).await
        }
        /// 处理HTTP请求 / Handle HTTP request
        pub async fn http_request(
            &mut self,
            request: impl tonic::IntoRequest<super::ForwardHttpReq>,
        ) -> std::result::Result<tonic::Response<super::HttpResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pluginproto.PluginService/HttpRequest",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pluginproto.PluginService", "HttpRequest"));
            self.inner.unary(req, path, codec).await
        }
        /// 获取频道消息 / Get channel messages
        pub async fn channel_message(
            &mut self,
            request: impl tonic::IntoRequest<super::ChannelMessageReq>,
        ) -> std::result::Result<
            tonic::Response<super::ChannelMessageResp>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pluginproto.PluginService/ChannelMessage",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pluginproto.PluginService", "ChannelMessage"));
            self.inner.unary(req, path, codec).await
        }
        /// 批量获取频道消息 / Batch get channel messages
        pub async fn channel_message_batch(
            &mut self,
            request: impl tonic::IntoRequest<super::ChannelMessageBatchReq>,
        ) -> std::result::Result<
            tonic::Response<super::ChannelMessageBatchResp>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pluginproto.PluginService/ChannelMessageBatch",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("pluginproto.PluginService", "ChannelMessageBatch"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// 获取频道所属节点 / Get channel belonging node
        pub async fn cluster_channel_belong_node(
            &mut self,
            request: impl tonic::IntoRequest<super::ClusterChannelBelongNodeReq>,
        ) -> std::result::Result<
            tonic::Response<super::ClusterChannelBelongNodeResp>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pluginproto.PluginService/ClusterChannelBelongNode",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "pluginproto.PluginService",
                        "ClusterChannelBelongNode",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// 批量获取频道所属节点 / Batch get channel belonging nodes
        pub async fn cluster_channel_belong_node_batch(
            &mut self,
            request: impl tonic::IntoRequest<super::ClusterChannelBelongNodeReq>,
        ) -> std::result::Result<
            tonic::Response<super::ClusterChannelBelongNodeBatchResp>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pluginproto.PluginService/ClusterChannelBelongNodeBatch",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "pluginproto.PluginService",
                        "ClusterChannelBelongNodeBatch",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// 获取最近会话频道 / Get recent conversation channels
        pub async fn conversation_channel(
            &mut self,
            request: impl tonic::IntoRequest<super::ConversationChannelReq>,
        ) -> std::result::Result<
            tonic::Response<super::ConversationChannelResp>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pluginproto.PluginService/ConversationChannel",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("pluginproto.PluginService", "ConversationChannel"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// 开启流 / Open stream
        pub async fn stream_open(
            &mut self,
            request: impl tonic::IntoRequest<super::Stream>,
        ) -> std::result::Result<tonic::Response<super::StreamOpenResp>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pluginproto.PluginService/StreamOpen",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pluginproto.PluginService", "StreamOpen"));
            self.inner.unary(req, path, codec).await
        }
        /// 关闭流 / Close stream
        pub async fn stream_close(
            &mut self,
            request: impl tonic::IntoRequest<super::StreamCloseReq>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pluginproto.PluginService/StreamClose",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pluginproto.PluginService", "StreamClose"));
            self.inner.unary(req, path, codec).await
        }
        /// 写入流 / Write stream
        pub async fn stream_write(
            &mut self,
            request: impl tonic::IntoRequest<super::StreamWriteReq>,
        ) -> std::result::Result<
            tonic::Response<super::StreamWriteResp>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pluginproto.PluginService/StreamWrite",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pluginproto.PluginService", "StreamWrite"));
            self.inner.unary(req, path, codec).await
        }
        /// 发送消息 / Send message
        pub async fn send(
            &mut self,
            request: impl tonic::IntoRequest<super::SendReq>,
        ) -> std::result::Result<tonic::Response<super::SendResp>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/pluginproto.PluginService/Send",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("pluginproto.PluginService", "Send"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod plugin_service_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with PluginServiceServer.
    #[async_trait]
    pub trait PluginService: Send + Sync + 'static {
        /// 插件启动 / Plugin startup
        async fn startup(
            &self,
            request: tonic::Request<super::PluginInfo>,
        ) -> std::result::Result<tonic::Response<super::StartupResp>, tonic::Status>;
        /// 处理发送包（消息发送前）/ Handle send packet (before message sent)
        async fn on_send_packet(
            &self,
            request: tonic::Request<super::SendPacket>,
        ) -> std::result::Result<tonic::Response<super::SendPacket>, tonic::Status>;
        /// 处理接收包（消息接收后）/ Handle receive packet (after message received)
        async fn on_recv_packet(
            &self,
            request: tonic::Request<super::RecvPacket>,
        ) -> std::result::Result<tonic::Response<super::RecvPacket>, tonic::Status>;
        /// 处理消息持久化后 / Handle after message persisted
        async fn on_persist_after(
            &self,
            request: tonic::Request<super::Message>,
        ) -> std::result::Result<tonic::Response<super::Message>, tonic::Status>;
        /// 处理回复消息 / Handle reply message
        async fn on_reply(
            &self,
            request: tonic::Request<super::Message>,
        ) -> std::result::Result<tonic::Response<super::Message>, tonic::Status>;
        /// 处理HTTP请求 / Handle HTTP request
        async fn http_request(
            &self,
            request: tonic::Request<super::ForwardHttpReq>,
        ) -> std::result::Result<tonic::Response<super::HttpResponse>, tonic::Status>;
        /// 获取频道消息 / Get channel messages
        async fn channel_message(
            &self,
            request: tonic::Request<super::ChannelMessageReq>,
        ) -> std::result::Result<
            tonic::Response<super::ChannelMessageResp>,
            tonic::Status,
        >;
        /// 批量获取频道消息 / Batch get channel messages
        async fn channel_message_batch(
            &self,
            request: tonic::Request<super::ChannelMessageBatchReq>,
        ) -> std::result::Result<
            tonic::Response<super::ChannelMessageBatchResp>,
            tonic::Status,
        >;
        /// 获取频道所属节点 / Get channel belonging node
        async fn cluster_channel_belong_node(
            &self,
            request: tonic::Request<super::ClusterChannelBelongNodeReq>,
        ) -> std::result::Result<
            tonic::Response<super::ClusterChannelBelongNodeResp>,
            tonic::Status,
        >;
        /// 批量获取频道所属节点 / Batch get channel belonging nodes
        async fn cluster_channel_belong_node_batch(
            &self,
            request: tonic::Request<super::ClusterChannelBelongNodeReq>,
        ) -> std::result::Result<
            tonic::Response<super::ClusterChannelBelongNodeBatchResp>,
            tonic::Status,
        >;
        /// 获取最近会话频道 / Get recent conversation channels
        async fn conversation_channel(
            &self,
            request: tonic::Request<super::ConversationChannelReq>,
        ) -> std::result::Result<
            tonic::Response<super::ConversationChannelResp>,
            tonic::Status,
        >;
        /// 开启流 / Open stream
        async fn stream_open(
            &self,
            request: tonic::Request<super::Stream>,
        ) -> std::result::Result<tonic::Response<super::StreamOpenResp>, tonic::Status>;
        /// 关闭流 / Close stream
        async fn stream_close(
            &self,
            request: tonic::Request<super::StreamCloseReq>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status>;
        /// 写入流 / Write stream
        async fn stream_write(
            &self,
            request: tonic::Request<super::StreamWriteReq>,
        ) -> std::result::Result<tonic::Response<super::StreamWriteResp>, tonic::Status>;
        /// 发送消息 / Send message
        async fn send(
            &self,
            request: tonic::Request<super::SendReq>,
        ) -> std::result::Result<tonic::Response<super::SendResp>, tonic::Status>;
    }
    /// 插件服务 / Plugin Service
    /// 注意：WuKongIM 的插件服务通常由插件实现，服务器调用插件的方法
    /// Note: WuKongIM's plugin service is usually implemented by plugins, and the
    /// server calls plugin methods
    #[derive(Debug)]
    pub struct PluginServiceServer<T: PluginService> {
        inner: _Inner<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    struct _Inner<T>(Arc<T>);
    impl<T: PluginService> PluginServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            let inner = _Inner(inner);
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for PluginServiceServer<T>
    where
        T: PluginService,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            let inner = self.inner.clone();
            match req.uri().path() {
                "/pluginproto.PluginService/Startup" => {
                    #[allow(non_camel_case_types)]
                    struct StartupSvc<T: PluginService>(pub Arc<T>);
                    impl<T: PluginService> tonic::server::UnaryService<super::PluginInfo>
                    for StartupSvc<T> {
                        type Response = super::StartupResp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PluginInfo>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PluginService>::startup(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = StartupSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pluginproto.PluginService/OnSendPacket" => {
                    #[allow(non_camel_case_types)]
                    struct OnSendPacketSvc<T: PluginService>(pub Arc<T>);
                    impl<T: PluginService> tonic::server::UnaryService<super::SendPacket>
                    for OnSendPacketSvc<T> {
                        type Response = super::SendPacket;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SendPacket>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PluginService>::on_send_packet(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = OnSendPacketSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pluginproto.PluginService/OnRecvPacket" => {
                    #[allow(non_camel_case_types)]
                    struct OnRecvPacketSvc<T: PluginService>(pub Arc<T>);
                    impl<T: PluginService> tonic::server::UnaryService<super::RecvPacket>
                    for OnRecvPacketSvc<T> {
                        type Response = super::RecvPacket;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RecvPacket>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PluginService>::on_recv_packet(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = OnRecvPacketSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pluginproto.PluginService/OnPersistAfter" => {
                    #[allow(non_camel_case_types)]
                    struct OnPersistAfterSvc<T: PluginService>(pub Arc<T>);
                    impl<T: PluginService> tonic::server::UnaryService<super::Message>
                    for OnPersistAfterSvc<T> {
                        type Response = super::Message;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::Message>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PluginService>::on_persist_after(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = OnPersistAfterSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pluginproto.PluginService/OnReply" => {
                    #[allow(non_camel_case_types)]
                    struct OnReplySvc<T: PluginService>(pub Arc<T>);
                    impl<T: PluginService> tonic::server::UnaryService<super::Message>
                    for OnReplySvc<T> {
                        type Response = super::Message;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::Message>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PluginService>::on_reply(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = OnReplySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pluginproto.PluginService/HttpRequest" => {
                    #[allow(non_camel_case_types)]
                    struct HttpRequestSvc<T: PluginService>(pub Arc<T>);
                    impl<
                        T: PluginService,
                    > tonic::server::UnaryService<super::ForwardHttpReq>
                    for HttpRequestSvc<T> {
                        type Response = super::HttpResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ForwardHttpReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PluginService>::http_request(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = HttpRequestSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pluginproto.PluginService/ChannelMessage" => {
                    #[allow(non_camel_case_types)]
                    struct ChannelMessageSvc<T: PluginService>(pub Arc<T>);
                    impl<
                        T: PluginService,
                    > tonic::server::UnaryService<super::ChannelMessageReq>
                    for ChannelMessageSvc<T> {
                        type Response = super::ChannelMessageResp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ChannelMessageReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PluginService>::channel_message(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = ChannelMessageSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pluginproto.PluginService/ChannelMessageBatch" => {
                    #[allow(non_camel_case_types)]
                    struct ChannelMessageBatchSvc<T: PluginService>(pub Arc<T>);
                    impl<
                        T: PluginService,
                    > tonic::server::UnaryService<super::ChannelMessageBatchReq>
                    for ChannelMessageBatchSvc<T> {
                        type Response = super::ChannelMessageBatchResp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ChannelMessageBatchReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PluginService>::channel_message_batch(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = ChannelMessageBatchSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pluginproto.PluginService/ClusterChannelBelongNode" => {
                    #[allow(non_camel_case_types)]
                    struct ClusterChannelBelongNodeSvc<T: PluginService>(pub Arc<T>);
                    impl<
                        T: PluginService,
                    > tonic::server::UnaryService<super::ClusterChannelBelongNodeReq>
                    for ClusterChannelBelongNodeSvc<T> {
                        type Response = super::ClusterChannelBelongNodeResp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ClusterChannelBelongNodeReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PluginService>::cluster_channel_belong_node(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = ClusterChannelBelongNodeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pluginproto.PluginService/ClusterChannelBelongNodeBatch" => {
                    #[allow(non_camel_case_types)]
                    struct ClusterChannelBelongNodeBatchSvc<T: PluginService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: PluginService,
                    > tonic::server::UnaryService<super::ClusterChannelBelongNodeReq>
                    for ClusterChannelBelongNodeBatchSvc<T> {
                        type Response = super::ClusterChannelBelongNodeBatchResp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ClusterChannelBelongNodeReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PluginService>::cluster_channel_belong_node_batch(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = ClusterChannelBelongNodeBatchSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pluginproto.PluginService/ConversationChannel" => {
                    #[allow(non_camel_case_types)]
                    struct ConversationChannelSvc<T: PluginService>(pub Arc<T>);
                    impl<
                        T: PluginService,
                    > tonic::server::UnaryService<super::ConversationChannelReq>
                    for ConversationChannelSvc<T> {
                        type Response = super::ConversationChannelResp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ConversationChannelReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PluginService>::conversation_channel(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = ConversationChannelSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pluginproto.PluginService/StreamOpen" => {
                    #[allow(non_camel_case_types)]
                    struct StreamOpenSvc<T: PluginService>(pub Arc<T>);
                    impl<T: PluginService> tonic::server::UnaryService<super::Stream>
                    for StreamOpenSvc<T> {
                        type Response = super::StreamOpenResp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::Stream>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PluginService>::stream_open(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = StreamOpenSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pluginproto.PluginService/StreamClose" => {
                    #[allow(non_camel_case_types)]
                    struct StreamCloseSvc<T: PluginService>(pub Arc<T>);
                    impl<
                        T: PluginService,
                    > tonic::server::UnaryService<super::StreamCloseReq>
                    for StreamCloseSvc<T> {
                        type Response = super::Empty;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StreamCloseReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PluginService>::stream_close(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = StreamCloseSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pluginproto.PluginService/StreamWrite" => {
                    #[allow(non_camel_case_types)]
                    struct StreamWriteSvc<T: PluginService>(pub Arc<T>);
                    impl<
                        T: PluginService,
                    > tonic::server::UnaryService<super::StreamWriteReq>
                    for StreamWriteSvc<T> {
                        type Response = super::StreamWriteResp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StreamWriteReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PluginService>::stream_write(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = StreamWriteSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/pluginproto.PluginService/Send" => {
                    #[allow(non_camel_case_types)]
                    struct SendSvc<T: PluginService>(pub Arc<T>);
                    impl<T: PluginService> tonic::server::UnaryService<super::SendReq>
                    for SendSvc<T> {
                        type Response = super::SendResp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SendReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PluginService>::send(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = SendSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        Ok(
                            http::Response::builder()
                                .status(200)
                                .header("grpc-status", "12")
                                .header("content-type", "application/grpc")
                                .body(empty_body())
                                .unwrap(),
                        )
                    })
                }
            }
        }
    }
    impl<T: PluginService> Clone for PluginServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: PluginService> Clone for _Inner<T> {
        fn clone(&self) -> Self {
            Self(Arc::clone(&self.0))
        }
    }
    impl<T: std::fmt::Debug> std::fmt::Debug for _Inner<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }
    impl<T: PluginService> tonic::server::NamedService for PluginServiceServer<T> {
        const NAME: &'static str = "pluginproto.PluginService";
    }
}
