// This file is @generated by prost-build.
/// 登录请求 / Login request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginRequest {
    /// 用户名 / Username
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    /// 密码 / Password
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
    /// 设备ID / Device ID
    #[prost(string, tag = "3")]
    pub device_id: ::prost::alloc::string::String,
    /// IP地址 / IP address
    #[prost(string, tag = "4")]
    pub ip: ::prost::alloc::string::String,
}
/// 登录响应 / Login response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginResponse {
    /// 状态 / Status
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    /// 访问令牌 / Access token
    #[prost(string, tag = "2")]
    pub token: ::prost::alloc::string::String,
    /// 用户ID / User ID
    #[prost(string, tag = "3")]
    pub uid: ::prost::alloc::string::String,
    /// 过期时间 / Expiration time
    #[prost(int64, tag = "4")]
    pub expires_at: i64,
}
/// 登出请求 / Logout request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogoutRequest {
    /// 用户ID / User ID
    #[prost(string, tag = "1")]
    pub uid: ::prost::alloc::string::String,
    /// 令牌 / Token
    #[prost(string, tag = "2")]
    pub token: ::prost::alloc::string::String,
}
/// 登出响应 / Logout response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogoutResponse {
    /// 状态 / Status
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
}
/// 踢出用户请求 / Kick out request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KickOutRequest {
    /// 用户ID / User ID
    #[prost(string, tag = "1")]
    pub uid: ::prost::alloc::string::String,
    /// 原因 / Reason
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
    /// 操作者ID / Operator UID
    #[prost(string, tag = "3")]
    pub operator_uid: ::prost::alloc::string::String,
}
/// 踢出用户响应 / Kick out response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KickOutResponse {
    /// 状态 / Status
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
}
/// Token 续期请求 / Token renew request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RenewTokenRequest {
    /// 用户ID / User ID
    #[prost(string, tag = "1")]
    pub uid: ::prost::alloc::string::String,
    /// 旧令牌 / Old token
    #[prost(string, tag = "2")]
    pub old_token: ::prost::alloc::string::String,
}
/// Token 续期响应 / Token renew response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RenewTokenResponse {
    /// 状态 / Status
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    /// 新令牌 / New token
    #[prost(string, tag = "2")]
    pub new_token: ::prost::alloc::string::String,
    /// 过期时间 / Expiration time
    #[prost(int64, tag = "3")]
    pub expires_at: i64,
}
/// Token 替换请求 / Token replaced request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenReplacedRequest {
    /// 用户ID / User ID
    #[prost(string, tag = "1")]
    pub uid: ::prost::alloc::string::String,
    /// 旧令牌 / Old token
    #[prost(string, tag = "2")]
    pub old_token: ::prost::alloc::string::String,
    /// 新令牌 / New token
    #[prost(string, tag = "3")]
    pub new_token: ::prost::alloc::string::String,
    /// 设备ID / Device ID
    #[prost(string, tag = "4")]
    pub device_id: ::prost::alloc::string::String,
}
/// Token 替换响应 / Token replaced response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenReplacedResponse {
    /// 状态 / Status
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
}
/// 用户封禁请求 / User ban request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BanUserRequest {
    /// 用户ID / User ID
    #[prost(string, tag = "1")]
    pub uid: ::prost::alloc::string::String,
    /// 原因 / Reason
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
    /// 封禁到期时间（0表示永久）/ Ban until (0 means permanent)
    #[prost(int64, tag = "3")]
    pub ban_until: i64,
    /// 操作者ID / Operator UID
    #[prost(string, tag = "4")]
    pub operator_uid: ::prost::alloc::string::String,
}
/// 用户封禁响应 / User ban response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BanUserResponse {
    /// 状态 / Status
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
}
/// Token 验证请求 / Token validate request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidateTokenRequest {
    /// 令牌 / Token
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
}
/// Token 验证响应 / Token validate response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidateTokenResponse {
    /// 状态 / Status
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    /// 是否有效 / Is valid
    #[prost(bool, tag = "2")]
    pub valid: bool,
    /// 用户ID / User ID
    #[prost(string, tag = "3")]
    pub uid: ::prost::alloc::string::String,
    /// 过期时间 / Expiration time
    #[prost(int64, tag = "4")]
    pub expires_at: i64,
}
