// This file is @generated by prost-build.
/// 保存消息请求 / Save message request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SaveMessageRequest {
    /// 消息ID / Message ID
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    /// 发送者UID / Sender UID
    #[prost(string, tag = "2")]
    pub from_uid: ::prost::alloc::string::String,
    /// 接收者UID / Receiver UID
    #[prost(string, tag = "3")]
    pub to_uid: ::prost::alloc::string::String,
    /// 消息内容 / Message content
    #[prost(string, tag = "4")]
    pub content: ::prost::alloc::string::String,
    /// 时间戳 / Timestamp
    #[prost(int64, tag = "5")]
    pub timestamp: i64,
    /// 消息类型 / Message type
    #[prost(string, tag = "6")]
    pub msg_type: ::prost::alloc::string::String,
}
/// 保存消息响应 / Save message response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SaveMessageResponse {
    /// 状态 / Status
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    /// 消息ID / Message ID
    #[prost(string, tag = "2")]
    pub message_id: ::prost::alloc::string::String,
}
/// 保存离线消息请求 / Save offline message request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SaveOfflineMessageRequest {
    /// 消息ID / Message ID
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    /// 接收者UID / Receiver UID
    #[prost(string, tag = "2")]
    pub to_uid: ::prost::alloc::string::String,
    /// 发送者UID / Sender UID
    #[prost(string, tag = "3")]
    pub from_uid: ::prost::alloc::string::String,
    /// 消息内容 / Message content
    #[prost(string, tag = "4")]
    pub content: ::prost::alloc::string::String,
    /// 时间戳 / Timestamp
    #[prost(int64, tag = "5")]
    pub timestamp: i64,
}
/// 保存离线消息响应 / Save offline message response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SaveOfflineMessageResponse {
    /// 状态 / Status
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    /// 消息ID / Message ID
    #[prost(string, tag = "2")]
    pub message_id: ::prost::alloc::string::String,
}
/// 离线消息 / Offline message
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OfflineMessage {
    /// 消息ID / Message ID
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    /// 发送者UID / Sender UID
    #[prost(string, tag = "2")]
    pub from_uid: ::prost::alloc::string::String,
    /// 消息内容 / Message content
    #[prost(string, tag = "3")]
    pub content: ::prost::alloc::string::String,
    /// 时间戳 / Timestamp
    #[prost(int64, tag = "4")]
    pub timestamp: i64,
}
/// 拉取离线消息请求 / Pull offline messages request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PullOfflineMessagesRequest {
    /// 用户UID / User UID
    #[prost(string, tag = "1")]
    pub uid: ::prost::alloc::string::String,
    /// 限制数量 / Limit count
    #[prost(int32, tag = "2")]
    pub limit: i32,
}
/// 拉取离线消息响应 / Pull offline messages response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PullOfflineMessagesResponse {
    /// 状态 / Status
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    /// 消息列表 / Message list
    #[prost(message, repeated, tag = "2")]
    pub messages: ::prost::alloc::vec::Vec<OfflineMessage>,
    /// 总数 / Total count
    #[prost(int32, tag = "3")]
    pub total: i32,
}
/// 确认离线消息请求 / Acknowledge offline messages request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AckOfflineMessagesRequest {
    /// 用户UID / User UID
    #[prost(string, tag = "1")]
    pub uid: ::prost::alloc::string::String,
    /// 消息ID列表 / Message ID list
    #[prost(string, repeated, tag = "2")]
    pub message_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// 确认离线消息响应 / Acknowledge offline messages response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AckOfflineMessagesResponse {
    /// 状态 / Status
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    /// 确认数量 / Acknowledged count
    #[prost(int32, tag = "2")]
    pub count: i32,
}
/// 统计离线消息请求 / Count offline messages request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CountOfflineMessagesRequest {
    /// 用户UID / User UID
    #[prost(string, tag = "1")]
    pub uid: ::prost::alloc::string::String,
}
/// 统计离线消息响应 / Count offline messages response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CountOfflineMessagesResponse {
    /// 状态 / Status
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    /// 消息数量 / Message count
    #[prost(int32, tag = "2")]
    pub count: i32,
}
/// 添加房间成员请求 / Add room member request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddRoomMemberRequest {
    /// 房间ID / Room ID
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    /// 用户UID / User UID
    #[prost(string, tag = "2")]
    pub uid: ::prost::alloc::string::String,
}
/// 添加房间成员响应 / Add room member response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddRoomMemberResponse {
    /// 状态 / Status
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
}
/// 移除房间成员请求 / Remove room member request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveRoomMemberRequest {
    /// 房间ID / Room ID
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    /// 用户UID / User UID
    #[prost(string, tag = "2")]
    pub uid: ::prost::alloc::string::String,
}
/// 移除房间成员响应 / Remove room member response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveRoomMemberResponse {
    /// 状态 / Status
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
}
/// 获取房间成员请求 / Get room members request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRoomMembersRequest {
    /// 房间ID / Room ID
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
}
/// 获取房间成员响应 / Get room members response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRoomMembersResponse {
    /// 状态 / Status
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    /// 成员列表 / Member list
    #[prost(string, repeated, tag = "2")]
    pub members: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
