// This file is @generated by prost-build.
/// HTTP 请求 / HTTP request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HttpRequest {
    /// HTTP 方法 / HTTP method (GET, POST, etc.)
    #[prost(string, tag = "1")]
    pub method: ::prost::alloc::string::String,
    /// 请求路径 / Request path
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    /// 请求头 / Request headers
    #[prost(map = "string, string", tag = "3")]
    pub headers: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// 请求体 / Request body
    #[prost(bytes = "vec", tag = "4")]
    pub body: ::prost::alloc::vec::Vec<u8>,
    /// 查询参数 / Query parameters
    #[prost(map = "string, string", tag = "5")]
    pub query_params: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// 客户端地址 / Client address
    #[prost(string, tag = "6")]
    pub remote_addr: ::prost::alloc::string::String,
}
/// HTTP 响应 / HTTP response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HttpResponse {
    /// HTTP 状态码 / HTTP status code
    #[prost(int32, tag = "1")]
    pub status_code: i32,
    /// 响应头 / Response headers
    #[prost(map = "string, string", tag = "2")]
    pub headers: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// 响应体 / Response body
    #[prost(bytes = "vec", tag = "3")]
    pub body: ::prost::alloc::vec::Vec<u8>,
}
/// 注册路由请求 / Register route request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterRouteRequest {
    /// 路由路径 / Route path
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    /// HTTP 方法 / HTTP method
    #[prost(string, tag = "2")]
    pub method: ::prost::alloc::string::String,
    /// 处理器名称 / Handler name
    #[prost(string, tag = "3")]
    pub handler: ::prost::alloc::string::String,
    /// 优先级 / Priority
    #[prost(int32, tag = "4")]
    pub priority: i32,
}
/// 注册路由响应 / Register route response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterRouteResponse {
    /// 状态 / Status
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    /// 路由ID / Route ID
    #[prost(string, tag = "2")]
    pub route_id: ::prost::alloc::string::String,
}
/// 注销路由请求 / Unregister route request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnregisterRouteRequest {
    /// 路由ID / Route ID
    #[prost(string, tag = "1")]
    pub route_id: ::prost::alloc::string::String,
}
/// 注销路由响应 / Unregister route response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnregisterRouteResponse {
    /// 状态 / Status
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
}
/// API 代理请求 / API proxy request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProxyRequest {
    /// 目标URL / Target URL
    #[prost(string, tag = "1")]
    pub target_url: ::prost::alloc::string::String,
    /// HTTP 方法 / HTTP method
    #[prost(string, tag = "2")]
    pub method: ::prost::alloc::string::String,
    /// 请求头 / Request headers
    #[prost(map = "string, string", tag = "3")]
    pub headers: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// 请求体 / Request body
    #[prost(bytes = "vec", tag = "4")]
    pub body: ::prost::alloc::vec::Vec<u8>,
    /// 超时时间（毫秒）/ Timeout in milliseconds
    #[prost(int32, tag = "5")]
    pub timeout_ms: i32,
}
/// API 代理响应 / API proxy response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProxyResponse {
    /// 状态 / Status
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    /// HTTP 状态码 / HTTP status code
    #[prost(int32, tag = "2")]
    pub status_code: i32,
    /// 响应头 / Response headers
    #[prost(map = "string, string", tag = "3")]
    pub headers: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// 响应体 / Response body
    #[prost(bytes = "vec", tag = "4")]
    pub body: ::prost::alloc::vec::Vec<u8>,
    /// 请求耗时（毫秒）/ Request duration in milliseconds
    #[prost(int32, tag = "5")]
    pub duration_ms: i32,
}
/// 健康检查请求 / Health check request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HealthCheckRequest {
    /// 服务名称 / Service name
    #[prost(string, tag = "1")]
    pub service: ::prost::alloc::string::String,
}
/// 健康检查响应 / Health check response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HealthCheckResponse {
    /// 状态 / Status
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    /// 是否健康 / Is healthy
    #[prost(bool, tag = "2")]
    pub healthy: bool,
    /// 消息 / Message
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
    /// 运行时间（秒）/ Uptime in seconds
    #[prost(int64, tag = "4")]
    pub uptime_seconds: i64,
}
/// WebSocket 消息 / WebSocket message
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WebSocketMessage {
    /// 连接ID / Connection ID
    #[prost(string, tag = "1")]
    pub connection_id: ::prost::alloc::string::String,
    /// 消息类型 / Message type (text, binary, ping, pong, close)
    #[prost(string, tag = "2")]
    pub message_type: ::prost::alloc::string::String,
    /// 消息数据 / Message data
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
/// WebSocket 响应 / WebSocket response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WebSocketResponse {
    /// 状态 / Status
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    /// 消息类型 / Message type
    #[prost(string, tag = "2")]
    pub message_type: ::prost::alloc::string::String,
    /// 响应数据 / Response data
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
