// This file is @generated by prost-build.
/// 握手请求 / Handshake request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HandshakeRequest {
    /// 插件名称 / Plugin name
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// 插件版本 / Plugin version
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    /// 能力列表 / Capabilities
    #[prost(string, repeated, tag = "3")]
    pub capabilities: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 优先级 / Priority
    #[prost(int32, tag = "4")]
    pub priority: i32,
    /// 支持的协议: "protobuf" / Supported protocol
    #[prost(string, tag = "5")]
    pub protocol: ::prost::alloc::string::String,
}
/// 握手响应 / Handshake response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HandshakeResponse {
    /// 状态: "ok" 或 "error" / Status: "ok" or "error"
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    /// 可选的消息 / Optional message
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// 配置数据（JSON字符串）/ Config data (JSON string)
    #[prost(string, tag = "3")]
    pub config: ::prost::alloc::string::String,
    /// 协商后的协议 / Negotiated protocol
    #[prost(string, tag = "4")]
    pub protocol: ::prost::alloc::string::String,
}
/// 事件消息 / Event message
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventMessage {
    /// 事件类型 / Event type
    #[prost(string, tag = "1")]
    pub event_type: ::prost::alloc::string::String,
    /// 事件载荷（Protobuf 二进制）/ Event payload (Protobuf binary)
    #[prost(bytes = "vec", tag = "2")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    /// 时间戳（毫秒）/ Timestamp in milliseconds
    #[prost(int64, tag = "3")]
    pub timestamp: i64,
    /// 可选的追踪ID / Optional trace ID
    #[prost(string, tag = "4")]
    pub trace_id: ::prost::alloc::string::String,
}
/// 事件响应 / Event response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventResponse {
    /// 状态: "ok", "error" / Status
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    /// 流控制: "continue", "stop" / Flow control
    #[prost(string, tag = "2")]
    pub flow: ::prost::alloc::string::String,
    /// 响应数据（Protobuf 二进制）/ Response data (Protobuf binary)
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// 错误信息（如果有）/ Error message if any
    #[prost(string, tag = "4")]
    pub error: ::prost::alloc::string::String,
}
