/*
File: v/src/comm/api/generator.rs
Purpose: Implement build-time generation of API route registry, route printing, module tree, and model trait impls.
Author: Auto-generated by Trae Assistant
Created: 2025-11-17
Copyright: © VGO Project. All rights reserved.

文件用途：实现构建期的 API 路由注册、路由打印函数、模块树以及模型接口实现的代码生成。
设计目标：保持与原 v-auth-center 的 build.rs 功能一致，同时更清晰的结构与错误处理。
*/

use anyhow::Result;
use std::path::Path;

mod model;
mod route;

/*
Function: run
Description: Generate code artifacts into OUT_DIR using sources under manifest/src.
Params:
- manifest_dir: Path string to crate manifest directory.
- out_dir: Path string to Cargo OUT_DIR.
Returns: Result<(), anyhow::Error>.
Exceptions: IO errors, missing directories.
Complexity: O(F) where F is number of files scanned.
Usage: generator::run(&manifest_dir, &out_dir)?;
中文说明：扫描 api 与 model 目录，生成路由注册与打印函数、模块树、模型接口实现，写入 OUT_DIR。
*/
pub fn run(manifest_dir: &str, out_dir: &str) -> Result<()> {
    println!("cargo:rerun-if-changed=src/api");
    println!("cargo:rerun-if-changed=src/model");
    // 生成 API 相关代码 / Generate API artifacts
    route::generate_api_artifacts(manifest_dir, out_dir)?;
    // 生成模型相关代码 / Generate model artifacts
    model::generate_model_artifacts(manifest_dir, out_dir)?;
    // 保证文件存在（编辑器诊断依赖）/ Ensure files exist for editor diagnostics
    for name in [
        "api_registry.rs",
        "auto_mod.rs",
        "model_auto.rs",
        "model_tree.rs",
    ] {
        let p = Path::new(out_dir).join(name);
        if !p.exists() {
            std::fs::write(&p, "// generated\n")?;
        }
    }
    Ok(())
}

pub fn run_for_auth_center() -> anyhow::Result<()> {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")?;
    let out_dir = std::env::var("OUT_DIR")?;
    run(&manifest_dir, &out_dir)
}

// Helpers moved into submodules / 助手函数已拆分至子模块
